# Generated by Django 2.2.5 on 2019-10-19 09:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articel_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotograf Ekle'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
