# Generated by Django 2.2.5 on 2019-11-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20191107_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(max_length=50, verbose_name='isim'),
        ),
    ]
